### ISSUE TITLE
Improve navbar

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/acm-fun#1]
make it nicey nice looking, looks trash rn

**Comment by sergomen** [comment]
I can work on this issue

**Comment by ken1000minus7** [comment]
Sure assigning

**Comment by tutrinh16** [comment]
Hey there! Can you assign me.

**Comment by ken1000minus7** [comment]
@tutrinh16 this issue is already assigned

**Comment by debopriyadey** [comment]
Hey @tutrinh16 can you assing this issue to me. As you can assign to multiple user and there have been no development on this issue till now

**Comment by ken1000minus7** [comment]
There is already a pr raised for this issue #31
