### ISSUE TITLE
Guess the flag 

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/acm-fun#14]
show flags and ask user to guess them the country and all,  exact features upto your imagination

**Comment by Abhishek-Sood** [comment]
I d like to try it please assign me

**Comment by ken1000minus7** [comment]
@Abhishek-Sood any updates?

**Comment by Abhishek-Sood** [comment]
sir having some errors ....trying my best..please wait

**Comment by ken1000minus7** [comment]
Sure np

**Comment by SanidhyaSharma28** [comment]
can i try?

**Comment by SanidhyaSharma28** [comment]
@ken1000minus7 can you assign it to me i will get it done in a day or two
