### ISSUE TITLE
Wordle

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/acm-fun#15]
make wordle

**Comment by SanidhyaSharma28** [comment]
i am interested can you assign it to me

**Comment by ken1000minus7** [comment]
@SanidhyaSharma28 any updates?

**Comment by SanidhyaSharma28** [comment]
@ken1000minus7 almost done if not today then will be done completely by tomorrow

**Comment by SanidhyaSharma28** [comment]
@ken1000minus7 can you check if its fine or not i have made a pull request
