### ISSUE TITLE
Change link embed information.

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/acm-fun#16]
- Currently default embed is shown. Add react logo in embed (present in assets) for now, and also fix the embed content. 
- Image and logo should be **in same line** for discord. How embed should look on other websites is upto you.

<details>

<summary> current embed in discord </summary>

![image](https://github.com/PEC-CSS/acm-fun/assets/75680424/5c959410-737a-4f57-add0-617384caaf12)

</details>

**Comment by taran1326** [comment]
Hey can you please assign me the issue , I want to work on it ?
