### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/acm-fun#18]
🙂

**Comment by markandey1414** [comment]
I'll do it @ken1000minus7 :), what stack I need to make it in?

**Comment by ken1000minus7** [comment]
Hi @markandey1414 , the app is built using react and you need to add the calculator as a new activity under activities

**Comment by markandey1414** [comment]
sure @ken1000minus7, I'll do it. Thanks @Ishwarendra for assigning

**Comment by karannakra** [comment]
Hi @ken1000minus7 I haven't seen any movement on this feature; could you kindly assign it to me?

**Comment by ken1000minus7** [comment]
Sure
