### ISSUE TITLE
Build home page

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/acm-fun#2]
make nicey nice home page explaining what this proj is about and what different sections are there and stuff

**Comment by sergomen** [comment]
Hello. Please assign me

**Comment by ken1000minus7** [comment]
Assigning one issue at a time rn

**Comment by sergomen** [comment]
Yeah, sure) Thank you

**Comment by tutrinh16** [comment]
Hey there! Can you assign me.

**Comment by ken1000minus7** [comment]
@tutrinh16 any updates?

**Comment by VaibhavGagneja** [comment]
@ken1000minus7 assign this to me and give a basic idea how the page should look like

**Comment by ken1000minus7** [comment]
It should be a landing page of the website and can contain 3 sections, the first one giving a brief about the website, then a brief about the games section and then about the activities section, other than that u can info about github repo and stuff, upto your imagination
