### ISSUE TITLE
Fortune Card Activity

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/acm-fun#29]
- Every fortune card should contain:
  - An image at top.
  - Title
  - Short Description.

- When a user clicks on `"Show my fortune button"`. Show him two distinct cards. If he is lucky, show him 3rd card.
- Being lucky is random. You can implement it in any way you want. 
- Some cards should be special and must have lesser probability of appearance than other.
- Atleast 15-20 card data should be present as described in point-1.

**Comment by GauravDhiman01** [comment]
Sir i am interested in this, please assign it to me

**Comment by YashM211** [comment]
Can I get this one
