### ISSUE TITLE
Improve UI of Random quote activity

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/acm-fun#44]
Make it nicer

**Comment by Arceen** [comment]
I made some changes. If you like it, I can send PR.
![image](https://github.com/PEC-CSS/acm-fun/assets/24473439/2fbcde35-1e15-4842-a582-eeb998f29026)
![image](https://github.com/PEC-CSS/acm-fun/assets/24473439/332c1113-6bd4-4f74-98c3-b8521343d14e)

**Comment by ken1000minus7** [comment]
Looks better, see if u can make anymore changes, assigning u
