### ISSUE TITLE
Changes to improve the current UI

### ISSUE THREAD

**Issue by Monika-1082005** [PEC-CSS/acm-fun#47]
**Here, proper margin could be added to enhance the UI & the text input could be made better**

![1](https://github.com/PEC-CSS/acm-fun/assets/134940879/03bc2390-d2fa-47d5-9668-f786678bb4a1)

**Also, in quotes generator we can add a cool font to match with the current UI**
![2](https://github.com/PEC-CSS/acm-fun/assets/134940879/eb27f33f-e172-4c0c-a192-882c81b4eea5)

If you will assign this than I can start working on it.

**Comment by ken1000minus7** [comment]
For the quotes generator there's a separate issue but u can work on the first one

**Comment by Monika-1082005** [comment]
Ok👍
