### ISSUE TITLE
Change title and logo

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/acm-fun#5]
Make nice logo, add it to the app in the required places and change the title

**Comment by ken1000minus7** [comment]
Sure

**Comment by ken1000minus7** [comment]
@Panth1823 any updates?

**Comment by sergomen** [comment]
I can work on it.

**Comment by sergomen** [comment]
@ken1000minus7, do I need to keep 'acm' abbreviation in a new title?

**Comment by ken1000minus7** [comment]
You can avoid changing the title, the title was default react app when this issue was created but we changed the title later on

**Comment by sergomen** [comment]
![image](https://github.com/PEC-CSS/acm-fun/assets/18175528/725027b8-8468-477e-a578-23777e314e94)
What is your favourite?

**Comment by ken1000minus7** [comment]
3rd one
