### ISSUE TITLE
Dog http status activity

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/acm-fun#83]
Show a dog image based on http code entered by user
can use this https://http.dog/

**Comment by konan625** [comment]
Can you asssign this to me?

**Comment by konan625** [comment]
Thank you for assigning this to me, Can you explain a little bit more what is exactly required , do you want a page or somthing that fetches all dog images from https://http.dog/ ? I would really appreciate an elaboration since its my first issue.
Thank you.

**Comment by ken1000minus7** [comment]
You need to make a simple activity with a text box where a user can input a status code and click on button/ press enter following which below the textbox an image should appear based on the status code entered, you can refer to this pr on how you need to add a new activity
https://github.com/PEC-CSS/acm-fun/pull/37/files
These are just the basic requirements though, you are free to innovate/design the activity the way u want to

**Comment by konan625** [comment]
ok thank you so much

**Comment by konan625** [comment]
@ken1000minus7 hey, I have completed this task, can you review it #89
